version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports: 
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "Lol12345"
        ACCEPT_EULA: 'Y'
    restart: always
    ports:
        - "1434:1433"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=Lol12345"
    depends_on:
        - orderdb
    ports:
        - "8004:80"

